version: '3.8'

# Global x-* fields for reuse
x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

x-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 20s

services:
  # 3x-ui VPN Panel - using a different, more reliable image
  xui:
    image: enwaiax/x-ui:latest
    container_name: xray-ui
    restart: unless-stopped
    ports:
      - 9001:54321 # Panel port (external:internal) - changed to avoid conflict
      - 9443:443   # HTTPS port (for Xray services) - changed to avoid conflict
      - 9080:80    # HTTP port (for certbot) - changed to avoid conflict
    environment:
      - TZ=${TIMEZONE:-Europe/Moscow}
      - XRAY_VMESS_AEAD_FORCED=${XRAY_VMESS_AEAD_FORCED:-false}
      - XUI_USERNAME=${XUI_USERNAME:-admin}
      - XUI_PASSWORD=${XUI_PASSWORD:-admin}
    volumes:
      - xui_db_data:/etc/x-ui/:rw
      - xui_cert_data:/root/cert/:ro
    networks:
      - vpn-network
    healthcheck:
      <<: *default-healthcheck
      test: [CMD, wget, -qO-, http://localhost:54321/]
    logging: *default-logging
    # Security and resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s

  # Admin Panel with Next.js and Supabase integration
  admin:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-https://dummy-value-for-build.supabase.co}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-dummy-key-for-build-only}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-/api}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:9002}
    container_name: vpn-admin
    restart: unless-stopped
    depends_on:
      - xui
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - XUI_PANEL_URL=http://xui:54321
      - XUI_USERNAME=${XUI_USERNAME:-admin}
      - XUI_PASSWORD=${XUI_PASSWORD:-admin}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET:-supersecretjwtsignkey}
      # Performance tuning
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
    ports:
      - 9002:3000  # Map container's 3000 port to host's 9002 - changed to avoid conflict
    networks:
      - vpn-network
    logging: *default-logging
    healthcheck:
      <<: *default-healthcheck
      test: [CMD, wget, -qO-, http://localhost:3000/]
    # Security and resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    read_only: false # Next.js needs write access
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  vpn-network:
    driver: bridge
    # Enhanced network security
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    driver_opts:
      com.docker.network.bridge.name: vpn0

# Named volumes for data persistence
volumes:
  xui_db_data:
    driver: local
  xui_cert_data:
    driver: local
