name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Deploy to Azure VM
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SERVER_IP: vpn-service.germanywestcentral.cloudapp.azure.com
        run: |
          ssh $SSH_USER@$SERVER_IP << 'EOF'
            # Navigate to project directory (create if it doesn't exist)
            if [ ! -d "vpnservice" ]; then
              git clone https://github.com/organicnz/vpnservice.git
              cd vpnservice
            else
              cd vpnservice
              git pull
            fi

            # Copy .env file if it doesn't exist
            if [ ! -f ".env" ]; then
              cp .env.example .env
              # Here you would edit .env with the correct values
              # For security, we've stored them as GitHub secrets
              echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
              echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
              echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env
              echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
            fi

            # Start or restart Docker services
            docker-compose down
            docker-compose up -d

            # Verify services are running
            docker ps
          EOF 