name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - development
      rebuild_type:
        description: "Type of rebuild"
        required: true
        default: "admin-only"
        type: choice
        options:
          - full
          - backend-only
          - admin-only
          - xui-only

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up SSH
        if: inputs.environment == "production"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Deploy and Fix Admin Panel
        if: inputs.environment == "production" && (inputs.rebuild_type == "admin-only" || inputs.rebuild_type == "full")
        env:
          SSH_USER: organic
          SERVER_IP: ${{ secrets.VPN_DOMAIN }}
        run: |
          ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new $SSH_USER@$SERVER_IP "cd ~/dev/vpnservice && \
            docker-compose stop admin && \
            echo \"NEXT_PUBLIC_API_URL=http://backend:3000\" >> .env && \
            echo \"NEXT_PUBLIC_SUPABASE_URL=\\${SUPABASE_URL}\" >> .env && \
            echo \"NEXT_PUBLIC_SUPABASE_ANON_KEY=\\${SUPABASE_KEY}\" >> .env && \
            docker-compose build --no-cache admin && \
            docker-compose up -d admin && \
            sleep 10 && \
            docker logs vpn-admin | tail -n 20"

  post-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Summary
        run: |
          echo "===== Deployment Summary ====="
          echo "Environment: ${{ inputs.environment }}"
          echo "Rebuild Type: ${{ inputs.rebuild_type }}"
          echo "Status: Completed"
          echo ""
          echo "Access your services at:"
          echo "VPN Admin Panel: http://vpn-service.germanywestcentral.cloudapp.azure.com:54321"
          echo "Backend API: http://vpn-service.germanywestcentral.cloudapp.azure.com:3000"
          echo "Admin Dashboard: http://vpn-service.germanywestcentral.cloudapp.azure.com:8080"
